--script de atualização da nota técnica NT_2015_002_v141 (23-08-2016)

INSERT INTO schema_nfe(idGrupo, campo, descricao, elemento, pai, tipo, ocorrencia, tamanho, observacao, nota_tecnica) VALUES('ID',   'Campo',       'Descrição',                                                            'Ele',  'Pai',  'Tipo', 'Ocor.',    'Ocor.',    'Observação', 'NT_2015_002_v141 (23-08-2016)');
INSERT INTO schema_nfe(idGrupo, campo, descricao, elemento, pai, tipo, ocorrencia, tamanho, observacao, nota_tecnica) VALUES('LA11', 'encerrante',  'Informações do grupo de “encerrante”',                                 'G',    'LA01', '',     '0-1',      '',         'Informações do grupo de “encerrante” disponibilizado\npor hardware específico acoplado à bomba de\ncombustível, definido no controle da venda do Posto\nRevendedor de Combustível.', 'NT_2015_002_v141 (23-08-2016)');
INSERT INTO schema_nfe(idGrupo, campo, descricao, elemento, pai, tipo, ocorrencia, tamanho, observacao, nota_tecnica) VALUES('LA12', 'nBico',       'Número de identificação do bico\n utilizado no abastecimento',         'E',    'LA11', 'N',    '1-1',      '1-3',      'Informar o número do bico utilizado no abastecimento.', 'NT_2015_002_v141 (23-08-2016)');
INSERT INTO schema_nfe(idGrupo, campo, descricao, elemento, pai, tipo, ocorrencia, tamanho, observacao, nota_tecnica) VALUES('LA13', 'nBomba',      'Número de identificação da bomba ao\n qual o bico está interligado',   'E',    'LA11', 'N',    '0-1',      '1-3',      'Caso exista, informar o número da bomba utilizada.', 'NT_2015_002_v141 (23-08-2016)');
INSERT INTO schema_nfe(idGrupo, campo, descricao, elemento, pai, tipo, ocorrencia, tamanho, observacao, nota_tecnica) VALUES('LA14', 'nTanque',     'Número de identificação do tanque ao\n qual o bico está interligado',  'E',    'LA11', 'N',    '1-1',      '1-3',      'Informar o número do tanque utilizado.', 'NT_2015_002_v141 (23-08-2016)');
INSERT INTO schema_nfe(idGrupo, campo, descricao, elemento, pai, tipo, ocorrencia, tamanho, observacao, nota_tecnica) VALUES('LA15', 'vEncIni',     'Valor do Encerrante no início do\n abastecimento',                     'E',    'LA11', 'N',    '1-1',      '12v3',     'Informar o valor da leitura do contador (Encerrante) no\n início do abastecimento', 'NT_2015_002_v141 (23-08-2016)');
INSERT INTO schema_nfe(idGrupo, campo, descricao, elemento, pai, tipo, ocorrencia, tamanho, observacao, nota_tecnica) VALUES('LA16', 'vEncFin',     'Valor do Encerrante no final do\n abastecimento',                      'E',    'LA11', 'N',    '1-1',      '12v3',     'Informar o valor da leitura do contador (Encerrante) no\n término do abastecimento', 'NT_2015_002_v141 (23-08-2016)');
UPDATE schema_nfe SET observacao = 'Campo será preenchido quando o campo anterior estiver preenchido. Informar o motivo da desoneração:\n1=Táxi;\n3=Produtor Agropecuário;\n4=Frotista/Locadora;\n5=Diplomático/Consular;\n6=Utilitários e Motocicletas da Amazônia Ocidental e Áreas de Livre Comércio (Resolução 714/88 e 790/94 – CONTRAN e suas alterações);\n7=SUFRAMA;\n8=Venda a Órgão Público;\n9=Outros. (NT 2011/004);\n10=Deficiente Condutor (Convênio ICMS 38/12);\n11=Deficiente Não Condutor (Convênio ICMS 38/12).\n16=Olimpíadas Rio 2016;\n\nRevogada a partir da versão 3.01 a possibilidade de usar o motivo 2=Deficiente Físico' WHERE id = 337;
UPDATE schema_nfe SET nota_tecnica = 'NT_2015_002_v141 (23-08-2016)' WHERE id = 337;
UPDATE schema_nfe SET tipo = 'N', observacao = 'Codificação conforme Anexo XIV - “Código de \nEnquadramento Legal do IPI”.', nota_tecnica = 'NT_2015_002_v141 (23-08-2016)' WHERE idGrupo = 'O06';
INSERT INTO schema_nfe(idGrupo, campo, descricao, elemento, pai, tipo, ocorrencia, tamanho, observacao, nota_tecnica) VALUES('YA04a', 'tpIntegra', 'Tipo de Integração para pagamento', 'E', 'YA04', 'N', '0-1', '1', 'Tipo de Integração do processo de pagamento com o\nsistema de automação da empresa:\n1=Pagamento integrado com o sistema de automação da\nempresa (Ex.: equipamento TEF, Comércio\nEletrônico);\n2= Pagamento não integrado com o sistema de\nautomação da empresa (Ex.: equipamento POS);\n', 'NT_2015_002_v141 (23-08-2016)');
UPDATE schema_nfe SET ocorrencia = '0-1', nota_tecnica = 'NT_2015_002_v141 (23-08-2016)' WHERE idGrupo = 'YA05';

